version: "3.8"
services:
    postgres-db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_DB=airflow
        # volumes:
        #     - ~/personal/github/airflow-local/db/data:/var/lib/postgresql/data
    redis-kv:
        image: redis:6.0
        ports:
          - 6379:6379
    airflow-dev:
        image: airflow-dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 5555:5555
        depends_on: 
            - postgres-db
            - redis-kv
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
        volumes:
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
