# Simplified version for local development.
version: "3.8"
services:
#    smtp-local:
#        image: namshi/smtp
#        ports:
#            - 25:25
    airflow-web:
        image: airflow-web
        entrypoint: ./scripts/airflow-all-start.sh
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 5555:5555
#        depends_on:
#            - smtp-local
        env_file: .env
        environment:
            - AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF= airflow-k8s-configmap
            - AIRFLOW__CORE__LOGGING_LEVEL=INFO
            - AIRFLOW__CORE__EXECUTOR=KubernetesExecutor
            - AIRFLOW__KUBERNETES__IN_CLUSTER=False
            - AIRFLOW__KUBERNETES__CONFIG_FILE=/opt/airflow/k8s-config/kube.config
            - AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY=rkoH1pVL.azurecr.io/airflow
            - AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG=1.10.12
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow
            - AIRFLOW__KUBERNETES__DELETE_WORKER_PODS="False"
            - AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE="False"
            - AIRFLOW__KUBERNETES__NAMESPACE=airflow-tls
            - AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM=azure-claim-dags
            - AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_POINT=/opt/airflow/dags
            - AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH=/opt/airflow/dags
            - AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM=azure-claim-logs
            - AIRFLOW__KUBERNETES__LOGS_VOLUME_SUBPATH=
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
            - AIRFLOW__WEBSERVER__AUTHENTICATE=False
            - AIRFLOW__WEBSERVER__RBAC=False
            - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.api.auth.backend.deny_all
            - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=True
        volumes:
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
            - ~/personal/github/airflow-local/bootstrap:/opt/airflow/scripts
            - ~/personal/github/airflow-local/plugins:/opt/airflow/plugins
            - ~/personal/github/airflow-local/bootstrap/metadata:/opt/airflow/k8s-config
