version: "3.8"
services:
    # Add postgres db
    airflow-dev:
        image: airflow-dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        # environment:
        #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=Add sqlalchemy connection string
        volumes:
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
