# Simplified version for local development.
version: "3.8"
services:
#    smtp-local:
#        image: namshi/smtp
#        ports:
#            - 25:25
    airflow-web:
        image: airflow-web
        entrypoint: ./scripts/airflow-all-start.sh
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 5555:5555
#        depends_on:
#            - smtp-local
        env_file: .env
        environment:
            - AIRFLOW__CORE__LOGGING_LEVEL=INFO
            - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
            - AIRFLOW__WEBSERVER__AUTHENTICATE=False
            - AIRFLOW__WEBSERVER__RBAC=False
            # - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.deny_all
            # - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=True
            - AZURE_AUTH_LOCATION=/opt/airflow/init/azure_eyes_only_auth.json
            - BOX_AUTH_LOCATION=/opt/airflow/init/box_eyes_only_config.json
        volumes:
            - ~/personal/github/airflow-on-aks/dags:/opt/airflow/dags
            - ~/personal/github/airflow-on-aks/bootstrap:/opt/airflow/scripts
            - ~/personal/github/airflow-on-aks/plugins:/opt/airflow/plugins
            - ~/personal/github/airflow-on-aks/bootstrap/metadata:/opt/airflow/init
