version: "3.8"
services:
    postgres-db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_DB=airflow
        # volumes:
        #     - ~/personal/github/airflow-local/db/data:/var/lib/postgresql/data
    redis-kv:
        image: redis:6.0
        ports:
            - 6379:6379
    smtp-local:
        image: namshi/smtp
        ports:
            - 25:25
    airflow-web:
        image: airflow-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - postgres-db
            - redis-kv
            - smtp-local
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
            - AIRFLOW__SMTP__SMTP_HOST=smtp-local
            - AIRFLOW__SMTP__SMTP_STARTTLS=False
#            - AIRFLOW_CONN_AA_PROD_DB=postgres://login:password@host:port/schema?param1=val1&param2=val2
#            - AIRFLOW_VAR_FOO_BAZ={"hello":"world"}
        volumes:
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
    airflow-scheduler:
        image: apache/airflow:1.10.12
        entrypoint: ./scripts/airflow-scheduler-start.sh
        ports:
            - 5555:5555
        depends_on:
            - postgres-db
            - redis-kv
            - smtp-local
            - airflow-web
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
            - AIRFLOW__SMTP__SMTP_HOST=smtp-local
            - AIRFLOW__SMTP__SMTP_STARTTLS=False
            - AZURE_AUTH_LOCATION=/opt/airflow/scripts/azureauth.json
        volumes:
            - ~/personal/github/airflow-local/scripts:/opt/airflow/scripts
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
    airflow-worker-1:
        image: apache/airflow:1.10.12
        entrypoint: ["airflow", "worker", "-q", "airworker_q1", "-cn", "worker-1"]
        depends_on:
            - postgres-db
            - redis-kv
            - smtp-local
            - airflow-web
            - airflow-scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
            - AIRFLOW__SMTP__SMTP_HOST=smtp-local
            - AIRFLOW__SMTP__SMTP_STARTTLS=False
            - AZURE_AUTH_LOCATION=/opt/airflow/scripts/azureauth.json
        volumes:
            - ~/personal/github/airflow-local/scripts:/opt/airflow/scripts
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
    airflow-worker-2:
        image: apache/airflow:1.10.12
        entrypoint: ["airflow", "worker", "-q", "airworker_q2", "-cn", "worker-2"]
        depends_on:
            - postgres-db
            - redis-kv
            - smtp-local
            - airflow-web
            - airflow-scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
            - AIRFLOW__SMTP__SMTP_HOST=smtp-local
            - AIRFLOW__SMTP__SMTP_STARTTLS=False
            - AZURE_AUTH_LOCATION=/opt/airflow/scripts/azureauth.json
        volumes:
            - ~/personal/github/airflow-local/scripts:/opt/airflow/scripts
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
