version: "3.8"
services:
    postgres-db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=sa
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_DB=airflow
        # volumes:
        #     - ~/personal/github/airflow-local/db/data:/var/lib/postgresql/data
    redis-kv:
        image: redis:6.0
        ports:
          - 6379:6379
    airflow-scheduler:
        image: airflow-scheduler
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres-db
            - redis-kv
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
            - AZURE_AUTH_LOCATION=/opt/airflow/scripts/azureauth.json
        volumes:
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
    airflow-web:
        image: apache/airflow:1.10.12
        entrypoint: ./scripts/airflow-web-start.sh
        ports:
            - 8080:8080
            - 5555:5555
        restart: on-failure
        depends_on:
            - postgres-db
            - redis-kv
            - airflow-scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CELERY__BROKER_URL=redis://redis-kv:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://sa:pwd@postgres-db/airflow
            - AIRFLOW__CORE__FERNET_KEY=kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc=
        volumes:
            - ~/personal/github/airflow-local/scripts:/opt/airflow/scripts
            - ~/personal/github/airflow-local/dags:/opt/airflow/dags
