# Testing
# kubectl exec redis-0 -c redis -- redis-cli -p 6379 set foo 10
# kubectl exec redis-2 -c redis -- redis-cli -p 6379 get foo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-kv
  namespace: default
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: redis
          image: redis:5.0.9
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # livenessProbe:
          #   exec:
          #     command:
          #       - airflow
          #       - info
          #       - --anonymize
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: airflow-redis
