# See: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-options
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-airflow
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: azurefile
  azureFile:
    secretName: az-file-secret
    shareName: airflow
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
---
