# See: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-options
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-dags
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
---