# See https://cert-manager.io/docs/configuration/acme/
# For dns01 challenges on Azure DNS, see https://cert-manager.io/docs/configuration/acme/dns01/azuredns/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  # namespace: default
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: shermanflan@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-tls
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
      # selector:
      #     dnsZones:
      #     - 0e3291ad39ab4cdbab81.eastus.aksapp.io
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: airflow-com
#   namespace: default
# spec:
#   # Secret names are always required.
#   secretName: airflow-com-tls
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   subject:
#     organizations:
#     - rko
#   # isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   # usages:
#   #   - server auth
#   #   - client auth
#   # commonName: 0cf33844e91741c88f93.eastus.aksapp.io
#   # At least one of a DNS Name, URI, or IP address is required.
#   dnsNames:
#   - airflow.0cf33844e91741c88f93.eastus.aksapp.io
#   - celery.0cf33844e91741c88f93.eastus.aksapp.io
#   # Issuer references are always required.
#   issuerRef:
#     name: letsencrypt-staging
#     # We can reference ClusterIssuers by changing the kind here.
#     # The default value is Issuer (i.e. a locally namespaced Issuer)
#     kind: ClusterIssuer # Issuer
#     # This is optional since cert-manager will default to this value however
#     # if you are using an external issuer, change this to that issuer group.
#     group: cert-manager.io
