# See https://cert-manager.io/docs/configuration/acme/
# For dns01 challenges on Azure DNS, see https://cert-manager.io/docs/configuration/acme/dns01/azuredns/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # Issuer
metadata:
  name: letsencrypt-prod
  # namespace: default
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: shermanflan@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory  # prod
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-tls
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
      # selector:
      #     dnsZones:
      #     - 0e3291ad39ab4cdbab81.eastus.aksapp.io
