apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
spec:
  restartPolicy: Never  # Always
  containers:
  - image: python:3.8-alpine
    imagePullPolicy: Always
    name: hello-world
    command:
      - "python"
      - -c
    args:
      - "print('hello world from aks')"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
