# See: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-options
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-dags
spec:
  selector:
    matchLabels:
      volume: azure-file-dags
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-scripts
spec:
  selector:
    matchLabels:
      volume: azure-file-scripts
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-init
spec:
  selector:
    matchLabels:
      volume: azure-file-init
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
