apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-k8s-configmap
  namespace: airflow-tls
data:
  AIRFLOW__KUBERNETES__AIRFLOW_CONFIGMAP: airflow-k8s-configmap
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: airflow-k8s-configmap
  AIRFLOW__CORE__LOGGING_LEVEL: INFO
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: rkoH1pVL.azurecr.io/airflow
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1.10.12
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
  AIRFLOW__KUBERNETES__NAMESPACE: airflow-tls
  AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: azure-claim-dags
  AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_POINT: /opt/airflow/dags
  # AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: /opt/airflow/dags
  AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: azure-claim-logs
  # AIRFLOW__KUBERNETES__LOGS_VOLUME_SUBPATH: ""
  # AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: ""
  AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: graph
  AIRFLOW__CORE__FERNET_KEY: "kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc="
  AIRFLOW_CORE_STORE_SERIALIZED_DAGS: "True"
  AIRFLOW_CORE_STORE_DAG_CODE: "True"
  AIRFLOW_CORE_MIN_SERIALIZED_DAG_FETCH_INTERVAL: "30"
  AIRFLOW__SMTP__SMTP_HOST: airflow-smtp-svc
  AIRFLOW__SMTP__SMTP_STARTTLS: "False"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: airflow@smtp.rikguz.com
  # AZURE_AUTH_LOCATION: /opt/airflow/az-sec/azure-auth
  # BOX_AUTH_LOCATION: /opt/airflow/box-sec/box-auth
