# https://kubernetes.github.io/ingress-nginx/examples/auth/client-certs/
# https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/ssl-redirect: "false"
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    # This secret must exist beforehand
    # The TLS secret must contain keys named tls.crt and tls.key 
    # that contain the certificate and private key to use for TLS.
    # The cert must also contain the subj-name host...
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
    - hosts:
      - airflow.e1af8c3dcb6e42b8bcf5.eastus.aksapp.io
      secretName: airflow-tls-secret
    - hosts:
      - celery.e1af8c3dcb6e42b8bcf5.eastus.aksapp.io
      secretName: celery-tls-secret
  rules:
    - host: airflow.e1af8c3dcb6e42b8bcf5.eastus.aksapp.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: airflow-web-service
              port: 
                number: 8080
    - host: celery.e1af8c3dcb6e42b8bcf5.eastus.aksapp.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: airflow-web-service
              port:
                number: 5555