apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
  namespace: airflow-tls
data:
  # Reference: https://github.com/apache/airflow/tree/1.10.12/airflow/config_templates
  load_examples: "True"
  AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: "graph"
  AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow"
  AIRFLOW__CELERY__BROKER_URL: "redis://airflow-redis-service:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://sa:pwd@airflow-postgres-service/airflow"
  AIRFLOW__CORE__FERNET_KEY: "kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc="
  AIRFLOW_CORE_STORE_SERIALIZED_DAGS: "True"
  AIRFLOW_CORE_STORE_DAG_CODE: "True"
  AIRFLOW_CORE_MIN_SERIALIZED_DAG_FETCH_INTERVAL: "30"
  AIRFLOW__SMTP__SMTP_HOST: "airflow-smtp-svc"
  AIRFLOW__SMTP__SMTP_STARTTLS: "False"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@smtp.rikguz.com"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
