apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-scheduler
      instance: airflow-scheduler-celery
      version: "1.0.0"
      component: scheduler
      part-of: airflow
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  # minReadySeconds: 60
  # progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        name: airflow-scheduler
        instance: airflow-scheduler-celery
        version: "1.0.0"
        component: scheduler
        part-of: airflow
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      volumes:
        - name: "az-dags"
          persistentVolumeClaim:
            claimName: azure-claim-dags
        - name: "az-scripts"
          persistentVolumeClaim:
            claimName: azure-claim-scripts
        - name: "az-init"
          persistentVolumeClaim:
            claimName: azure-claim-init
      initContainers:
        - name: airflow-wait-web
          image: busybox:1.32.0
          command: ['sh', '-c', "until nslookup airflow-web-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for airflow-web-service; sleep 2; done"]
      containers:
        - name: airflow
          image: rkoH1pVL.azurecr.io/airflow:1.10.12
          imagePullPolicy: Always  # IfNotPresent
          command:
              - "./scripts/airflow-scheduler-start.sh"
          volumeMounts:
            - name: "az-dags"
              mountPath: "/opt/airflow/dags"
            - name: "az-scripts"
              mountPath: "/opt/airflow/scripts"
            - name: "az-init"
              mountPath: "/opt/airflow/init"
          env:
            - name: AIRFLOW__CORE__LOGGING_LEVEL
              value: "INFO"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://airflow-redis-service:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CORE__FERNET_KEY
              value: "kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc="
            - name: AIRFLOW_CORE_STORE_SERIALIZED_DAGS
              value: "True"
            - name: AIRFLOW_CORE_STORE_DAG_CODE
              value: "True"
            - name: AIRFLOW_CORE_MIN_SERIALIZED_DAG_FETCH_INTERVAL
              value: "30"
            - name: AIRFLOW__SMTP__SMTP_HOST
              value: "airflow-smtp-svc"
            - name: AIRFLOW__SMTP__SMTP_STARTTLS
              value: "False"
          resources:
            requests:
              cpu: "1000m"
              memory: "500Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # livenessProbe:
          #   exec:
          #     command:
          #       - airflow
          #       - info
          #       - --anonymize
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
