# TEST:
# Use ping: kubectl run curl --image=radial/busyboxplus:curl -i --tty
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: airflow-web-deploy
  namespace: default
spec:
  # Number of pods which should exist at all times
  replicas: 1
  selector:
    matchLabels:
      name: airflow-web
      instance: airflow-web-celery
      version: "1.0.0"
      component: web
      part-of: airflow
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  # revisionHistoryLimit: 3
  # minReadySeconds: 60
  # progressDeadlineSeconds: 600
  # Pods
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        name: airflow-web
        instance: airflow-web-celery
        version: "1.0.0"
        component: web
        part-of: airflow
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      # Create using kubectl create secret rko.acr.io my-image-pull-secret ...
      # imagePullSecrets:
      #   - name:  my-image-pull-secret
      volumes:
        - name: "az-dags"
          persistentVolumeClaim:
            claimName: azure-claim-dags
        - name: "az-scripts"
          persistentVolumeClaim:
            claimName: azure-claim-scripts
        - name: "az-init"
          persistentVolumeClaim:
            claimName: azure-claim-init
        # Create config using kubectl create configmap
        # - name: "config"
        #   configMap:
        #     name: my-config
        # Create secret using
        # kubectl create secret tls ssl --cert=server.crt --key=server.key
        # - name: certs
        #   secret:
        #     secretName: ssl
      initContainers:
        - name: airflow-wait-db
          image: busybox:1.32.0
          command: ['sh', '-c', "until nslookup airflow-postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for airflow-postgres-service; sleep 2; done"]
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
        - name: airflow-init-db
          image: rkoH1pVL.azurecr.io/airflow:1.10.12
          imagePullPolicy: Always  # IfNotPresent
          command:
              - "./scripts/airflow-init.sh"
          volumeMounts:
            - name: "az-scripts"
              mountPath: "/opt/airflow/scripts"
            - name: "az-init"
              mountPath: "/opt/airflow/init"
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://airflow-redis-service:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CORE__FERNET_KEY
              value: "kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc="
            - name: AIRFLOW__WEBSERVER__RBAC
              value: "True"
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: "True"
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      containers:
        - name: airflow
          image: rkoH1pVL.azurecr.io/airflow:1.10.12
          # image: rkoH1pVL.azurecr.io/airflow:1.10.12-slate
          imagePullPolicy: Always  # IfNotPresent
          command:
              - "./scripts/airflow-web-start.sh"
          volumeMounts:
            - name: "az-dags"
              mountPath: "/opt/airflow/dags"
            - name: "az-scripts"
              mountPath: "/opt/airflow/scripts"
            - name: "az-init"
              mountPath: "/opt/airflow/init"
            # - name: "config"
            #   mountPath: "/data/my-config"
            # - name: certs
            #   mountPath: "/ssl"
            #   readOnly: true
          env:
            - name: AIRFLOW__CORE__LOGGING_LEVEL
              value: "INFO"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://airflow-redis-service:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://sa:pwd@airflow-postgres-service/airflow"
            - name: AIRFLOW__CORE__FERNET_KEY
              value: "kLtLiPlyj8qyGolY_FB2CiRu1oNyX_ullQ2Q9KYb3wc="
            - name: AIRFLOW_CORE_STORE_SERIALIZED_DAGS
              value: "True"
            - name: AIRFLOW_CORE_STORE_DAG_CODE
              value: "True"
            - name: AIRFLOW_CORE_MIN_SERIALIZED_DAG_FETCH_INTERVAL
              value: "30"
            - name: AIRFLOW__SMTP__SMTP_HOST
              value: "airflow-smtp-svc"
            - name: AIRFLOW__SMTP__SMTP_STARTTLS
              value: "False"
            - name: AIRFLOW__WEBSERVER__RBAC
              value: "True"
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: "True"
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: az-oauth-secret
                  key: azure-tenant-id
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: az-oauth-secret
                  key: azure-app-id
            - name: AZURE_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: az-oauth-secret
                  key: azure-app-key
            # - name: FROM_CONFIG_MAP
            #   valueFrom:
            #     configMapKeyRef:
            #       name: my-config
            #       key: another-param
          resources:
            requests:
              cpu: "1000m"
              memory: "500Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: celery
              containerPort: 5555
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # livenessProbe:
          #   exec:
          #     command:
          #       - airflow
          #       - info
          #       - --anonymize
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
---
# kubectl expose is a synonym for this stanza
apiVersion: v1
kind: Service
metadata:
  name: airflow-web-service
  labels:
    name: airflow-web-service
    instance: airflow-web-celery
    version: "1.0.0"
    component: web
    part-of: airflow
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: celery
      port: 5555
      targetPort: 5555
  selector:
    # Load balance traffic across Pods matching
    # this label selector
    name: airflow-web
    instance: airflow-web-celery
    version: "1.0.0"
    component: web
    part-of: airflow
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: airflow-web-hpa
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 1 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airflow-web-deploy
  targetCPUUtilizationPercentage: 60 # target CPU utilization
